### ISSUE TITLE
[question] All my configurations are Empty ActiveSupport:OrderedOptions

### ISSUE THREAD

**Issue by ninovanhooff** [dhh/custom_configuration#4]
Ruby 2.1.5
Rails 4.0.13

config/environments/development.rb

```
JumboSIP::Application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  module Devise
    module LdapAdapter
      def self.valid_credentials?(login, password)
        return true
      end
    end
  end

  config.cache_store = :memory_store

  config.log_level = :debug

  config.assets.compile = true

  # In the development environment your application's code is reloaded on
  # every request. This slows down response time but is perfect for development
  # since you don't have to restart the web server when you make code changes.
  config.cache_classes = false

  # Do not eager load code on boot.
  config.eager_load = false

  [..etc]

  # ------------------------------------
  # Application-specific configuration
  # ------------------------------------

  # use active directory auythentication (only for production)
  config.x.use_ad_auth = false
 # Enable to create cockpit cache files
  config.x.cockpit_cache_enabled = false

```

config/initializers/scheduler.rb

```
if Rails.configuration.x.cockpit_cache_enabled
      Rails.logger.info 'Initializing Cockpit Cache Scheduler'
      puts 'Initializing Cockpit Cache Scheduler'
```

The code in the if is reached while it should not.
Debug inspection shows that Rails.configuration.x.cockpit_cache_enabled evaluates to Empty ActiveSupport:OrderedOptions. 
Rails.configuration.x is of type CustomConfiguration::Configuration

I checked I am actually in development environment.

Any clue as to why this happens? Any conflicts with other gems.
If I uses orderedoptions outside this gem, behaviour is as expected

**Comment by lserman** [comment]
Just ran into this again on a 4.1 app and remembered I made a PR for it last year. @dhh I know you're a busy guy but any chance you could cut a new version with the fix?

**Comment by dhh** [comment]
This gem is deprecated from my end. Feel free to fork and continue the work. I'd be happy to point to a new home in the README.
